export const LOGINROUTER = '/login'
export const REGISTROUTER = '/register'
export const DASHBOARDROUTER = '/dashboard'
export const WORKSESSIONROUTER = '/workSession'
export const TASKROUTER = '/task'
export const TASKLOGROUTER = '/taskLog'
export const DEVICEROUTER = '/device'
export const ADMINROUTER = '/admin'